// 1. Mobile Menu Toggle
const menuToggle = document.getElementById('menuToggle');
const navLinks = document.getElementById('navLinks');

if (menuToggle) {
    menuToggle.addEventListener('click', () => {
        navLinks.classList.toggle('active');
    });
}

// 2. Widget Tab Switcher Logic
const tabBtns = document.querySelectorAll('.tab-btn');
tabBtns.forEach(btn => {
    btn.addEventListener('click', () => {
        tabBtns.forEach(b => b.classList.remove('active'));
        btn.classList.add('active');
    });
});

// 3. Dynamic Travel Planner Generator
const plannerForm = document.getElementById('plannerForm');
const plannerResult = document.getElementById('plannerResult');

if (plannerForm) {
    plannerForm.addEventListener('submit', (e) => {
        e.preventDefault();
        
        const destination = document.getElementById('destination').value.trim();
        const days = parseInt(document.getElementById('days').value);

        const activities = [
            "Explore historic downtown, iconic landmarks, and city views.",
            "Sample local street food specialties and visit traditional markets.",
            "Visit top-rated museums, art galleries, and cultural heritage sites.",
            "Take a relaxing stroll through scenic national parks or waterfronts.",
            "Experience vibrant night markets, rooftop lounges, and shopping districts."
        ];

        let resultHTML = `
            <div class="card" style="text-align: left; margin-top: 25px; border-left: 5px solid var(--primary-color); padding: 25px;">
                <h3 style="color: var(--primary-dark); margin-bottom: 15px; font-size: 1.3rem;">
                    <i class="fas fa-map-marked-alt"></i> ${days}-Day Itinerary Outline for ${destination}
                </h3>
                <ul style="padding-left: 20px; line-height: 1.8;">
        `;

        for (let i = 1; i <= days; i++) {
            const act = activities[(i - 1) % activities.length];
            resultHTML += `<li style="margin-bottom: 10px;"><strong>Day ${i}:</strong> ${act} in <em>${destination}</em>.</li>`;
        }

        resultHTML += `
                </ul>
                <div style="margin-top: 20px; padding-top: 15px; border-top: 1px solid var(--border-color); text-align: right;">
                    <small style="color: #718096;">Generated by Plyndi Smart Engine</small>
                </div>
            </div>
        `;

        plannerResult.innerHTML = resultHTML;
    });
}
